### ISSUE TITLE
PyTorch with CUDA

### ISSUE THREAD

**Issue by jbaron** [bytedeco/javacpp-presets#1038]
Start using the new PyTorch binding and have to say, it is really nice. Even without any additional Java/Kotlin wrapper the preset is already usable, I guess partially because the C++ API follows the Python API closely.

I'm now trying to get to CUDA support working (Ubuntu 20.04), but getting this exception:

      Exception in thread "main" java.lang.RuntimeException: CUDA error: the provided PTX was compiled with an unsupported toolchain.

Seems to be a mismatch of some CUDA libraries. I thought the preset comes with its own versions of CUDA libraries, but I noticed at least one library is  loaded from my machine installation (and not the maven installed libraries):

    ldd /home/peter/.javacpp/cache/pytorch-1.8.1-1.5.6-20210428.184934-66-linux-x86_64-gpu.jar/org/bytedeco/pytorch/linux-x86_64-gpu/libtorch_cuda.so
    ...
    libnvToolsExt.so.1 => /usr/local/cuda-11.1/targets/x86_64-linux/lib/libnvToolsExt.so.1
    ...

Can this be the cause of the exception and it it necessary to install also locally the same CUDA version as is used by the PyTorch preset ?

Thanks in advance!!!

**Comment by saudet** [comment]
Yeah, I'm not too sure what to do about libnvToolsExt.so.1, but it does appear to be distributed with CUDA consistently, so it should be added I think.

In any case, that's not the issue here. That error probably just means your video driver is too old. Make sure that you've installed the very latest version available from NVIDIA like the one from this month.

If you have any suggestions for PyTorch itself, please see the thread at https://github.com/bytedeco/javacpp-presets/issues/623#issuecomment-809961732. Thanks!

**Comment by jbaron** [comment]
Thanks, will try to update the driver itself (without breaking the rest of my system ;) and see if that indeed solves the issue.

**Comment by saudet** [comment]
Another thing you could do is simply to rebuild PyTorch with whatever version of CUDA that is installed on your machine. If you do this though, please make sure to specify the compute capabilities of your GPU here to avoid JIT compilation of PTX code:
https://github.com/bytedeco/javacpp-presets/blob/master/pytorch/cppbuild.sh#L15

**Comment by jbaron** [comment]
FYI, updated driver to latest version for my Linux distro and still get the same error.  My current version is now at:

        NVRM: loading NVIDIA UNIX x86_64 Kernel Module  460.73.01  Thu Apr  1 21:40:36 UTC 2021

So I guess something else is not playing nicely. 

So next will be rebuilding the Javacpp preset. Can I can just download a PyTorch C++ package (after making sure those work) and then rerun the preset make file against those libraries and header files?  Or does Javacpp also need access to the PyTorch source code itself and do I need to recompile PyTorch?

**Comment by saudet** [comment]
The latest driver version is 465, not 460.

**Comment by jbaron** [comment]
Thanks!!! indeed just found 465.24.02, so will try that one next,

**Comment by saudet** [comment]
BTW, @HGuillemet was able to do what he needed to do with CUDA and everything, see https://github.com/bytedeco/javacpp-presets/issues/623#issuecomment-846602486, so if you have any blocking issues, please let us know about them, and he should be able to help you right away.

**Comment by saudet** [comment]
I'm assuming it works now? If not, please let me know!
